[workspace]
members = [
    "crates/wcash-pool-backend-client",
    "crates/wcash-pool-core",
    "crates/wcash-pool-protocol",
    "crates/wcash-poold",
]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.1"
authors = ["RustNinja <placex.com@gmail.com>"]
edition = "2021"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
repository = "https://github.com/w-cash/pool"
homepage = "https://github.com/w-cash/pool"

[workspace.dependencies]
clap = { version = "4.5.47", features = ["derive"] }
hex = "0.4.3"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
uuid = { version = "1.18.1", features = ["serde", "v4"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"
