network = "mainnet"
deployment_id = "af99f42c-f66d-4332-acd2-8eebbe154da0"
pool_instance = "0dc35474-492b-41ca-82a7-7e1e80e056da"
backend_instance = "f1567968-da72-481f-bb95-4713f773cad9"
journal_stream = "dbd6fa80-f906-40c0-b4be-b69cd14f353c"
chain_id = 1464025427
wcash_genesis = "48fcb61b1d862d62f1a51810b50c8f127c131aaf9115ce047b572a66c812ae5b"
zcash_genesis = "08ce3d9731b000c08338455c8a4a6bd05da16e26b11daa1b917184ece80f0400"
wcash_payout_commitment = "c87744f400951411587bfdd98c74a299808bb752289a64814b9eff25a5b4f51d"
zcash_payout_commitment = "540fcc6310cf24e0592eb2f5ef4aa6332d67d1675141ef6326885686d1165d51"
backend_socket = "/run/zecwec-pool-staging/backend.sock"
database_url_file = "/etc/zecwec-pool-staging/database-url"
stratum_listen = "0.0.0.0:3339"
portal_listen = "127.0.0.1:18082"
portal_origin = "https://pool.zecwec.com"
registration_open = true
payout_change_hold_secs = 0
nonce_namespace = 4
nonce_reservation = 65536
database_connections = 4
maximum_miners = 64
maximum_miners_per_ip = 8
authentication_parallelism = 4
mining_authentication = "username_only"
wcash_wallet_program = "/opt/zecwec-pool-staging/wcash-wallet"
wcash_wallet_sha256 = "3e1d3ce397363f4f95a083bc4d9759fca67d20ec936ac2e768583a6f8e38f7bd"
wcash_wallet_uid = 0
payout_mode = "deferred"
wcash_node_rpc = "127.0.0.1:48232"
wcash_node_cookie_file = "/etc/zecwec-pool-staging/wcash-node.cookie"
zcash_node_rpc = "127.0.0.1:18232"
zcash_node_cookie_file = "/etc/zecwec-pool-staging/zcash-node.cookie"
portal_token_pepper_file = "/etc/zecwec-pool-staging/portal-pepper"
portal_totp_key_file = "/etc/zecwec-pool-staging/portal-totp"
initial_share_target_be = "0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
easiest_share_target_be = "0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

[wcash_policy]
pplns_window_work = "100000000"
payout_threshold_zat = 1000000
required_confirmations = 100
payout_confirmations = 3
maximum_payout_outputs = 1
minimum_payout_zat = 100000000
maximum_payout_zat = 10000000000
payout_skip_bps = 2000
maximum_network_fee_zat = 100000
maximum_network_fee_bps = 100
policy_version = 1

[zcash_policy]
pplns_window_work = "4000000000000"
payout_threshold_zat = 1000000
required_confirmations = 100
payout_confirmations = 3
maximum_payout_outputs = 50
minimum_payout_zat = 100000000
maximum_payout_zat = 100000000
payout_skip_bps = 0
maximum_network_fee_zat = 100000
maximum_network_fee_bps = 100
policy_version = 1
